### PR TITLE
Import template stories via 3 techniques

### PR DESCRIPTION
**Pull request by tmeasday**
I wonder if there's any easy way to switch between these outside of commenting things in and out (or having 3 files).

Only using the third setup do I see the desired behaviour (as I navigate between stories): 

image

image

### CODE REVIEW

**Review by bebraw — APPROVED** [review]
If we used separate files, we could control which one to pick through resolve.alias in webpack.

**Comment by tmeasday** [comment]
Refactored to take `IMPORT` as an option; can you take a look and check if it looks right to you?

**Comment by tmeasday** [comment]
On this branch lazy compilation is totally working if you pass `IMPORT=static`, with the obvious caveat that the imports are static ;)

**Review by bebraw — APPROVED** [review]
Looks good. Nice use of alias.

**Pull request merged**
